### PR TITLE
feat: Change dependent packages to Git submodules

### PR DESCRIPTION
**Pull request by takumin**
Close: #26

### CODE REVIEW

**Comment by masnagam** [comment]
The Pull Reuqest GA failed but I conformed that all unit tests passed on macOS.

The failures in the Pull Request GA are caused in `actions/checkout@v2`.  Because we need to change it like below:

```yaml
    steps:
      - uses: actions/checkout@v2
        with:
          submodule: recursive
```

Workflow YAML files are generated by `.github/workflows/update.sh` from `.github/workflows/templated/*.yml`.  After modifying the template YAML files, we need to run `sh ./github/workflows/update.sh`.

I created a patch for this issue: [ga.patch.txt](https://github.com/mirakc/mirakc-arib/files/7356568/ga.patch.txt).

**Comment by takumin** [comment]
Thank you very much for your review! I'm on the go now, so I'll check again when I get home.

**Comment by takumin** [comment]
Thank you for checking the operation of macOS, careful review, and providing patches!

I applied the patch you gave me and pushed it to the branch.

I would be grateful if you could review it when you have time!

**Comment by masnagam** [comment]
Thank you for your contribution! I'm going to merge it to the main branch.

**Pull request merged**
